### ISSUE TITLE
ABS_Brake_Pressure based on manually pressing the brakes while stationary

### ISSUE THREAD

**Issue by gdincu** [gdincu/HyundaiElantraCN7-OBD2-PIDs#3]
To also test this while in motion and under braking to ensure that it won't go over 100%

**Comment by umarov** [comment]
I tested this on my 2024 Elantra N (CN7N). The N mode display also has a brake % display. It closely matches. 

![Screenshot_20240815_181338_RaceChrono Pro](https://github.com/user-attachments/assets/7aceb13e-9790-4fb1-9b0a-56f3563bd18d)


https://ddns.mumarov.com:443/photo/mo/sharing/UT3lk0Dwt this is a link to the video with the data overlay from RaceChronoPro 

Oil temp is also from this GitHub.

**Comment by gdincu** [comment]
Thanks a lot for sharing this as I don't get that many chances of braking hard. Glad to hear it actually works as intended 🙂

**Comment by umarov** [comment]
I shared it with the N track community. There will be a lot of hard braking tests done and with data thanks to you!
